#=======================================================================================
# Global Config
#=======================================================================================
spring:
  application:
    name: dashboardservice
  profiles:
    active: "dev"
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          custom:
            authorization-grant-type: client_credentials
            client-id: callcentre-dashboard-project
            client-secret: '78a772d6-5947-49cf-b86f-772ded30bf54'
            provider: customprovider
        provider:
          customprovider:
            token-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master

# Actuator endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /_/
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
  exposure.include: '*'
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST, PUT
    allowed-headers: '*'

dashboardservice:
  dataServiceUrl: SETINENV
  adminService: SETINENV

---
#=======================================================================================
# Development Profile Config
#=======================================================================================
spring:
  profiles: dev
server:
  port: 8080


---
#=======================================================================================
# Production ProfileConfig - ALL CONFIG SHOULD BE PASSED AS ENV VARIABLES
#=======================================================================================
spring:
  profiles: production
server:
  port: 8080